[pytest]
addopts =
    --alluredir=reports/allure-results
    --clean-alluredir

testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    smoke: smoke test cases
    regression: regression test cases
    sanity: sanity test cases

log_cli = true
log_cli_level = INFO
